controllers_security:
    resource: ../../src/Controller/Security
    type: annotation

controllers_front:
    resource: ../../src/Controller/Front
    type: annotation

controllers_back:
    resource: ../../src/Controller/Back
    type: annotation
    prefix: /{_locale}/admin
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
    name_prefix: back_

kernel:
    resource: ../../src/Kernel.php
    type: annotation
